### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 160905** [AlphaBrock/91porn#3]
运行`pythons main.py`

```
Traceback (most recent call last):
  File "/Users/tiger/91porn/main.py", line 12, in <module>
    from libs.asyncSpider import Spider
  File "/Users/tiger/91porn/libs/asyncSpider.py", line 16, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by 160905** [comment]
`python3 main.py`
